language: node_js

node_js:
  - '14'
  - '12'
  - '10'

os:
  - linux
  - osx

env:
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=latest
  - WEBPACK_VERSION=next

install:
  - npm install
  - npm rm webpack
  - npm install webpack@$WEBPACK_VERSION || true

branches:
  only:
    - master
